language: rust

sudo: required

matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      rust: nightly

env:
  - CODECOV_TOKEN="4dad02c5-a383-4b0f-a78d-1d80f7ca8662"

rust:
  - nightly

jobs:
  include:
    - stage: test
      script:
        - cargo test --verbose --all
    - stage: build
      script: cargo build --verbose --all --release

before_deploy:
  - export TRAVIS_TAG="1.0.$TRAVIS_BUILD_NUMBER"
  - echo "$TRAVIS_TAG" "$TRAVIS_COMMIT"
  - git config --local user.name "$USER_NAME"
  - git config --local user.email "$USER_EMAIL"
  - git tag "$TRAVIS_TAG" "$TRAVIS_COMMIT"
deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  overwrite: true
  api_key: $GITHUB_API_KEY
  file: target/release/lunchtime
  skip_cleanup: true
  on:
    branch: async

branches:
  only:
    - async