[package]
name = "lunchtime"
version = "0.1.0"
authors = ["marcus.scalpere <marcus.scalpere@gmail.com>"]
edition = "2018"

[dependencies]
select = "0.4.2"
reqwest = "0.9.18"
hyper = "0.12"
tokio = "0.1.21"
futures = "0.1.28"
encoding = "0.2.33"
chrono = "0.4.7"
regex = "1.1.7"
lazy_static = "1.3.0"