enum_discrim_align_threshold = 70
struct_field_align_threshold = 70
use_field_init_shorthand = true
merge_imports = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
reorder_impl_items = true